# Define current workspace
workspace:
  base: /test
  path: ec_europa

# Define running services
services:
  mysql:
    image: fpfis/mysql56
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/ec_europa/build

# Define the pipeline
pipeline:
###
# Prepare & test section :
  install:
    image: fpfis/php56-dev
    commands:
      - composer self-update --ansi
      - composer install --ansi
    volumes:
      - /cache:/cache

  install-project:
    image: fpfis/php56-dev
    commands:
      - "./vendor/bin/robo project:setup-behat -o 'site.base_url: http://web:8080'"
      - "./vendor/bin/robo project:install -o 'database.host: mysql'"
    volumes:
      - /cache:/cache

  test:
    image: fpfis/php56-dev
    commands:
      - ./vendor/bin/grumphp run


###
# Demo section
  # Send status to slack #ci channel when demo starts
  slack-notify-demo-start:
    image: plugins/slack
    channel: ci
    username: fpfisbot
    icon_url: https://avatars0.githubusercontent.com/u/23079543?v=3&s=400
    secrets: [ slack_webhook ]
    # Run only on pr from demo/* to master :
    when:
      event: pull_request
      refspec: demo/*:master
    template: >
      {{repo.name}}@{{build.branch}} <https://${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-demo.ci.fpfis.tech.ec.europa.eu|demo {{build.number}}> started.

  # Starts a demo
  start-demo:
    image: fpfis/drone-frpc-plugin:latest
    secrets: [ frpc_token, frpc_server ]
    endpoint: web:8080
    gen_auth: yes
    domain: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-demo.ci.fpfis.tech.ec.europa.eu
    url_output_file: /test/ec_europa/.frpc
    # Run only on pr from demo/* to master :
    when:
      event: pull_request
      refspec: demo/*:master