# Define current workspace
workspace:
  base: /test
  path: ec_europa

# Define running services
services:
  mysql:
    image: fpfis/mysql56
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/ec_europa/build

# Define the pipeline
pipeline:

  install:
    image: fpfis/php56-dev
    commands:
      - composer self-update --ansi
      - composer install --ansi

  install-project:
    image: fpfis/php56-dev
    commands:
      - "./vendor/bin/robo project:install -o 'database.host: mysql' -o 'site.base_url: http://web:8080'"

  test:
    image: fpfis/php56-dev
    commands:
      - ./vendor/bin/grumphp run
