version: "2"

services:

  web:
    image: fpfis/php56-dev
    ports:
      - "8888:8888"
      - "8889:8889"
    volumes:
      - .:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      COMPOSER_MEMORY_LIMIT: 2G

  mysql:
    image: fpfis/mysql56